# Generated by Django 6.0.5 on 2026-06-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prisoner_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('identification_mark', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='prisoners_photos/')),
                ('crimes', models.CharField()),
                ('arrest_date', models.DateField()),
                ('phone_number', models.CharField(max_length=10)),
                ('fingerprint', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('under_trial', 'Under Trial'), ('convicted', 'Convicted'), ('released', 'Released')], default='under_trial', max_length=20)),
                ('arresting_officer', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
